<?php $this->layout('layout::layout', [
    'title' => 'Laminas Community',
]) ?>
<div class="row">
    <div class="col-md-2 col-sm-12">
        &nbsp;
    </div>

    <div class="col-md-7 col-sm-12 content" role="main" data-spy="scroll" data-target=".toc">
        <h4>Slack</h4>

        <ul>
            <li><a href="https://laminas.slack.com">Visit the Slack</a></li>
            <li><a href="https://join.slack.com/t/laminas/shared_invite/enQtNTkyMzExNzAxMzMwLWU3MjI2MGNlM2EyNWQzZDg4NTMzNDM2NzQ1ZDU2ZDJiNDVhZDQyZDczOThjNGIwOWNiODQ0YzE1NTA3NGU2YTA">Need an invite?</a></li>
        </ul>

        <h4>Forums</h4>

        <ul>
            <li><a href="https://discourse.laminas.dev">Join our
                Discourse</a></li>
        </ul>

    </div>

    <div class="col-md-3 col-sm-12 sidebar">
        &nbsp;
    </div>
</div>
