<?php $this->layout('layout::layout', []) ?>

<div class="row">
    <div class="col-md-2 col-sm-12">
        &nbsp;
    </div>

    <div class="col-md-7 col-sm-12 content" role="main" data-spy="scroll" data-target=".toc">
        <h4>Coming Soon!</h4>

        <p>
            This site is still in development. In the meantime, visit
            the <a href="https://docs.laminas.dev">documentation and tutorials</a>.
        </p>
    </div>

    <div class="col-md-3 col-sm-12 sidebar">
        &nbsp;
    </div>
</div>
