<?php

declare(strict_types=1);

/**
 * @var League\Plates\Template\Template $this
 */

$this->layout('layout::layout', ['redirect' => true]);
?>

<div class="row">
    <div class="col-md-2 col-sm-12">
        &nbsp;
    </div>

    <div class="col-md-7 col-sm-12 content" role="main" data-spy="scroll" data-target=".toc">
        <h4>Welcome to the Laminas Project!</h4>

        <p>
            Resources for developers:
        </p>

        <ul>
            <li><a href="https://getlaminas.org">Project website</a></li>
            <li><a href="https://github.com/laminas">GitHub</a></li>
            <li><a href="https://docs.laminas.dev">Documentation and tutorials</a></li>
            <li><a href="/chat">Community resources (Slack, forums)</a></li>
        </ul>
    </div>

    <div class="col-md-3 col-sm-12 sidebar">
        &nbsp;
    </div>
</div>
