name: laminas_dev

type: php:8.3

size: S

disk: 256

build:
  flavor: none

dependencies:
  php:
    composer/composer: "~2.5.8"

mounts:
  'data/cache':
    source: local
    source_path: data/cache

hooks:
  build: |
    set -e
    OPENSWOOLE_VERSION=22.1.2
    echo "Installing Swoole extension"
    bash install-swoole.sh openswoole "$OPENSWOOLE_VERSION"
    echo "Current PHP modules:"
    php -m
    echo "Installing platform.sh CLI"
    curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | bash
    echo "- Setting up configuration"
    rm -f config/development.config.php config/autoload/*.local.php
    mv config/autoload/local.php.dist config/autoload/local.php
    echo "- Installing application dependencies"
    composer install --no-ansi --no-dev --no-interaction --no-scripts --no-plugins --optimize-autoloader --ignore-platform-req=ext-openswoole
  deploy: |
    rm -rf data/cache/*

crons:
    snapshot:
        # Take a snapshot automatically every night at 3 am (UTC).
        spec: '0 3 * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform snapshot:create --yes --no-wait
            fi
    renewcert:
        # Force a redeploy at 8 am (UTC) on the 14th and 28th of every month.
        spec: '0 8 14,28 * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform redeploy --yes --no-wait
            fi

web:
  commands:
    start: 'php vendor/bin/laminas mezzio:swoole:start'
  upstream:
    socket_family: tcp
    protocol: http
  locations:
    '/':
      passthru: true
