<?php $this->layout('layout::layout', [
    'title' => 'Error',
]); ?>
<section class="col-6 code_500">
    <h2>An error occurred!</h2>

    <p>
        An error of some sort occurred! It's not you, it's me... Try again later. If it still doesn't work,
        <a href="/chat">contact us via chat</a>.
    </p>

    <?php if ($error) : ?>
    <pre><?= $this->e($error) ?></pre>
    <?php endif ?>
</section>
